### ISSUE TITLE
WinX64 - Closing debugscreen while wallet is minimised causes crash

### ISSUE THREAD

**Issue by FornaxNLG** [Gulden/gulden-official#142] opened 2018-12-05 17:07 UTC
### Can you reliably reproduce the issue?
Yes, 2.0.0.17 (Windows10/x64) 

#### If so, please list the steps to reproduce below:
1. Have the desktopwallet open
2. Open the debugscreen
3. Minimise the wallet
4. Close the debugscreen, wallet now crashes. 

### Expected behaviour
You'd expect the debugscreen to be closed but the wallet itself continu running, be it minimised.

### Actual behaviour
Upon closing the debugscreen the wallet crashes and gives an error dialog where you need to [Abort].
(If in this dialog I choose [Ignore] a new error occurs and the box and wallet close after 0.2 seconds)

### What version of Gulden are you using?
Downloaded from GitHub, 2.0.0.17 though error has been reported in the wild for earlier version.

### Machine specs:
- OS: Win10
- CPU: Intel i3-3770k
- RAM: 8GB
- Disk size: 250GB (113GB free)
- Disk Type (HD/SDD): SSD

![crashuponminimisingdebugscreen](https://user-images.githubusercontent.com/35969914/49530487-9d357f80-f8b8-11e8-9a5c-1c445c83401d.png)

**Comment by robobit** [comment] 2019-06-05 12:23
Unable to reproduce on current build, tried official build 2.1.0.4 and current unity branch on msys2/MinGW development build on Windows 10 and Windows Server 2016.
Likely this was fixed along the way with other work (Qt upgrade for example). Should the issue still occur on a recent build please re-open.

**Comment by robobit** [comment] 2019-06-05 12:37
Still occurs, to reproduce the _Minimize to tray instead of taskabar_ setting needs to be enabled in Settings->Options->Window.

**Comment by robobit** [comment] 2019-06-07 11:53
Fixed by d0ebd886c88f048db7dcc4822bd49e7fff321076

**Comment by mjmacleod** [comment] 2019-10-03 14:08
Need to backport this to 2.1 branch

**Comment by mjmacleod** [comment] 2019-10-15 22:08
Backported to 2.1 branch so should be fixed there as well now.

**Closed by mjmacleod** 2019-10-15 22:08 UTC
Labels: beginner_difficulty, bug, help wanted
